config/routes.rb
PrescriptionIntegration::Application.routes.draw do

  resources :medicos_autorizados

  get "venda/search"

  get "api/sign_in"

  get "receita_medicas/show_for_farmacia"
  
  get "receita_medicas/show_for_medico"
  get "receita_medicas/search"

  post "receita_medicas/vender"
  
  devise_for :users
  # ,  
  #             :controllers => {
  #               :registrations => 'devise/registrations',
  #               :sessions => 'devise/sessions',
  #             }
  
  resources :users
  resources :historicos

  resources :receita_medicas

  root      :to => 'welcome#index'
  resources :principio_ativos
  resources :medicamentos
  resources :farmacias
  resources :enderecos

  match "/medicos" => "users#medicos"
  match "/pacientes" => "users#pacientes"
end

app/models/receita_medica.rb
class ReceitaMedica < ActiveRecord::Base
	has_many :item_receitas
	has_many :medicamentos, :through => :item_receitas

	belongs_to :paciente, :class_name => 'User', :foreign_key =>'paciente_id', :conditions => "tipo = 1"
	belongs_to :medico, :class_name => 'User', :foreign_key =>'medico_id', :conditions => "tipo = 2"
	belongs_to :status

	accepts_nested_attributes_for :item_receitas

	def belongs_to_patient?(paciente_cpf)
		self.paciente.cpf == paciente_cpf
	end

	def pode_ser_vendida?
		self.status_id == Status.find_by_nome('Pendente').id || self.status_id == Status.find_by_nome('Uso continuo').id
	end
end

app/controllers/receita_medicas_controller.rb
class ReceitaMedicasController < ApplicationController
  before_filter :authenticate_user!
  # GET /receita_medicas
  # GET /receita_medicas.json
  def index
    
    if current_user.tipo == 2
      @receita_medicas = ReceitaMedica.where(:medico_id => current_user.id)
    elsif current_user.tipo == 1
      @receita_medicas = ReceitaMedica.where(:paciente_id => current_user.id)
    elsif current_user.tipo == 3
      @receita_medicas = Venda.receitas_medicas(current_user.id)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @receita_medicas }
    end
  end

  # GET /receita_medicas/1
  # GET /receita_medicas/1.json
  def show
    @receita_medica = ReceitaMedica.find(params[:id])
    @item_receitas = @receita_medica.item_receitas.all
    respond_to do |format|
      format.html # show.html.erb                                                
      format.json { render json: {
        :receita => @receita_medica, 
        :medicamentos => @receita_medica.item_receitas.collect {|t| [t.medicamento.nome, t.posologia, t.quantidade]} } }
    end
  end                                                                     
  
  # GET /receita_medicas/new
  # GET /receita_medicas/new.json
  def new
   raise 'Operacao invalida' unless current_user.tipo == 2
   @receita_medica = ReceitaMedica.new
   @medicamentos = Medicamento.all
   @users = User.Pacientes
   @historicos = Historico.all
   @receita_medica.item_receitas.build
   respond_to do |format|
     format.html # new.html.erb
     format.json { render json: @receita_medica }
   end
 end

  # GET /receita_medicas/1/edit
  def edit
    @receita_medica = ReceitaMedica.find(params[:id])
    @medicamentos = Medicamento.all
  end

  # POST /receita_medicas
  # POST /receita_medicas.json
  def create
    @receita_medica = ReceitaMedica.new(params[:receita_medica])
    @receita_medica.medico = current_user

    respond_to do |format|
      if @receita_medica.save
        format.html { redirect_to @receita_medica, notice: 'Receita medica was successfully created.' }
        format.json { render json: @receita_medica, status: :created, location: @receita_medica }
      else
        format.html { render action: "new" }
        format.json { render json: @receita_medica.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /receita_medicas/1
  # PUT /receita_medicas/1.json
  def update
    @receita_medica = ReceitaMedica.find(params[:id])

    respond_to do |format|
      if @receita_medica.update_attributes(params[:receita_medica])
        format.html { redirect_to @receita_medica, notice: 'Receita medica was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @receita_medica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receita_medicas/1
  # DELETE /receita_medicas/1.json
  def destroy
    @receita_medica = ReceitaMedica.find(params[:id])
    @receita_medica.destroy

    respond_to do |format|
      format.html { redirect_to receita_medicas_url }
      format.json { head :no_content }
    end
  end

  def show_for_farmacia
    if params[:search_cpf] && params[:search_receita] && current_user.tipo == 3
      @receita_medica = ReceitaMedica.where(:id => params[:search_receita])
      @receita_medica = @receita_medica.to_a.first
      if !@receita_medica.nil? && (@receita_medica.belongs_to_patient?(params[:search_cpf]) || Autorizado.where(:cpf => params[:search_cpf], :user_id => @receita_medica.paciente_id).to_a.size > 0)
        redirect_to @receita_medica 
      else       
        flash[:error] = 'Receita nao encontrada'
        redirect_to venda_search_path
      end
    else
      raise 'Operacao invalida'
    end
  end

  def show_for_medico
    if params[:search_cpf] && params[:search_receita] && current_user.tipo == 2
      @receita_medica = ReceitaMedica.find(params[:search_receita])
  
      if !@receita_medica.nil? && (@receita_medica.medico_id == current_user.id || MedicosAutorizado.where(:medico_id => current_user.id, :user_id => @receita_medica.paciente_id).to_a.size > 0)
        redirect_to @receita_medica, :editable => @receita_medica.medico_id == current_user.id
      else       
        flash[:error] = 'Receita nao encontrada'
        redirect_to venda_search_path
      end
    else
      raise 'Operacao invalida'
    end
  end

  def vender
    venda = Venda.new(:farmacia_id => params[:farmacia], :receita_medica_id => params[:receita])
    venda.save
    @receita_medica = ReceitaMedica.find(params[:receita])
    @receita_medica.status_id = Status.find_by_nome('Finalizado').id if @receita_medica.status_id == Status.find_by_nome('Pendente').id
    @receita_medica.save

    flash[:msg] = 'Venda da receita registrada com sucesso!'
    redirect_to @receita_medica
  end
end

app/helpers/receita_medicas_helper.rb
module ReceitaMedicasHelper
end

app/views/receita_medicas/_form.html.erb
<%= form_for @receita_medica, :html => { :class => 'form-horizontal' } do |f| %>
 <fieldset>
   <div class="control-group">
     <%= f.label :paciente_id, :class => 'control-label' %>
     <div class="controls">
        <%= @receita_medica.paciente.nome%>
     </div>
   </div>

   <div class="control-group">
     <%= f.label :status_id, :class => 'control-label' %>
     <div class="controls">
        <%= select(:receita_medica, :status_id, Status.all.map{|u|[u.nome, u.id]})%>
     </div>
   </div>

   <h3>Atualizar</h3>
   <%= f.fields_for :item_receitas do |builder| %>
    <%= render 'update_item_receita_fields', :f => builder %>
   <% end %>
         <%= link_to_add_fields "Adicionar Medicamento", f, :item_receitas, { :id => 'add_medicamento_link', :class => 'btn btn-info', :style => 'margin-bottom: 20px;' } %>

   <div class="form-actions">
     <%= f.submit nil, :class => 'btn btn-primary' %>
     <%= link_to 'Cancelar', receita_medicas_path, :class => 'btn' %>
   </div>
 </fieldset>
<% end %>

app/views/receita_medicas/_item_receita_fields.html.erb
  <div class="well fields"> 
    <%= link_to_destroy_fields "remover", f, :class => "close" %>
    <div class="control-group">
      <%= f.label :quantidade, :class => 'control-label' %>
      <div class="controls medicamento-select">
        <%= f.text_field :quantidade %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :posologia, :class => 'control-label' %>
      <div class="controls medicamento-select">
        <%= f.text_field :posologia %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :medicamento_id, :class => 'control-label' %>
      <div class="controls medicamento-select">
        <%= f.collection_select :medicamento_id, @medicamentos, :id, :nome %>
      </div>
    </div>
  </div>

app/views/receita_medicas/_update_item_receita_fields.html.erb
  <div class="well fields"> 
    <%= link_to_destroy_fields "remover", f, :class => "close" %>
    <div class="control-group">
      <%= f.label :quantidade, :class => 'control-label' %>
      <div class="controls medicamento-select">
        <%= f.text_field :quantidade %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :posologia, :class => 'control-label' %>
      <div class="controls medicamento-select">
        <%= f.text_field :posologia %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :medicamento_id, :class => 'control-label' %>
      <div class="controls medicamento-select">
        <%= f.collection_select :medicamento_id, @medicamentos, :id, :nome %>
      </div>
    </div>
  </div>

app/views/receita_medicas/edit.html.erb
<h2>Editar receita</h2>
<%= render :partial => 'form' %>

app/views/receita_medicas/index.html.erb
<h1>Receitas</h1>
<% if @receita_medicas %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Código</th>
        <th>Médico</th>
        <th>Paciente</th>
        <th>Data de Prescrição</th>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @receita_medicas.each do |receita_medica| %>
        <tr>
          <td><%= link_to receita_medica.id, receita_medica %></td>
          <td><%= link_to receita_medica.medico.crm, user_path(receita_medica.medico)%></td>
          <td><%= receita_medica.paciente.cpf %>
          <td><%= receita_medica.created_at.strftime("%d/%m/%Y")  %></td>
          <td><%= receita_medica.status.nome %>
          <td>
            <%= link_to 'Editar', edit_receita_medica_path(receita_medica), :class => 'btn btn-mini' if current_user.tipo == 2 %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if current_user.tipo == 2 %>
  	<%= link_to 'Nova receita', new_receita_medica_path, :class => 'btn' %>
  <% end %>
<% else %>
  <p>Não há receitas cadastradas, deseja criar uma?</p>
  <%= link_to 'Nova receita', new_receita_medica_path, :class => 'btn' %>
<% end %>

app/views/receita_medicas/new.html.erb
<h2>Nova receita</h2>
<%= form_for @receita_medica, :html => { :class => 'form-horizontal' } do |f| %>
 <fieldset>
   <div class="control-group">
     <%= f.label :paciente_id, :class => 'control-label' %>
     <div class="controls">
        <%= f.collection_select :paciente_id, @users, :id, :cpf%>
     </div>
   </div>

   <div class="control-group">
     <%= f.label :status_id, :class => 'control-label' %>
     <div class="controls">
        <%= select(:receita_medica, :status_id, [Status.find_by_nome('Pendente'), Status.find_by_nome('Uso continuo')].map{|u|[u.nome, u.id]})%>
     </div>
   </div>

   <h3>Novo medicamento</h3>
   <%= f.fields_for :item_receitas do |builder| %>
    <%= render 'item_receita_fields', :f => builder %>
   <% end %>
    <%= link_to_add_fields "Adicionar Medicamento", f, :item_receitas, { :id => 'add_medicamento_link', :class => 'btn btn-info', :style => 'margin-bottom: 20px;' } %>

   <div class="form-actions">
     <%= f.submit 'Criar receita', :class => 'btn btn-primary' %>
     <%= link_to 'Cancelar', receita_medicas_path, :class => 'btn' %>
   </div>
 </fieldset>
<% end %>

app/views/receita_medicas/search.html.erb
<h3>Pesquisar por receita</h3>
<p>
	<%= flash[:error] if flash[:error] %>
</p>
<%= form_tag('/receita_medicas/show_for_medico', :method => :get)  do %>
	<p>
		CPF <br/> <%= text_field_tag :search_cpf%></br>
		Código da receita <br/> <%= text_field_tag :search_receita %></br>
		<%= submit_tag "Procurar" %>
	</p>
<% end %>

app/views/receita_medicas/show.html.erb
<h1>Receita Médica</h1>

<%= flash[:msg] if !flash[:msg].nil? %>

<p>
  <b>Medico</b><br>
  <%= @receita_medica.medico.crm %> - <%= @receita_medica.medico.nome %>
</p>

<p>
  <b>Paciente</b><br>
  <%= @receita_medica.paciente.cpf %>
</p>

<p>
  <b>Status</b><br>
  <%= @receita_medica.status.nome %>
</p>

<p>
  <b>Data prescricao</b><br>
  <%= @receita_medica.created_at.strftime("%d/%m/%Y")  %>
</p>

<h2> Medicamentos </h2>
  <% for item_receita in @receita_medica.item_receitas %>
    <p>
      <strong>Medicamento: </strong><%= item_receita.medicamento.nome %><br>
      <strong>Quantidade: </strong><%= item_receita.quantidade %><br>
      <strong>Posologia: </strong><%= item_receita.posologia %>
    </p>
  <% end %>
<div class="form-actions">
  <%= link_to 'Voltar', receita_medicas_path, :class => 'btn'  %>
  <%= link_to 'Editar', edit_receita_medica_path(@receita_medica), :class => 'btn' if !params[:editable].nil? || (params[:editable]) %>
  <br/> <br/>
  <%= button_to 'Vender', {:action => 'vender', :remote => true, :receita => @receita_medica.id, :farmacia => current_user.id } if @receita_medica.pode_ser_vendida? && current_user.tipo == 3 %>
</div>