config/routes.rb
PrescriptionIntegration::Application.routes.draw do

  resources :medicos_autorizados

  get "venda/search"

  get "api/sign_in"

  get "receita_medicas/show_for_farmacia"
  
  get "receita_medicas/show_for_medico"
  get "receita_medicas/search"

  post "receita_medicas/vender"
  
  devise_for :users
  # ,  
  #             :controllers => {
  #               :registrations => 'devise/registrations',
  #               :sessions => 'devise/sessions',
  #             }
  
  resources :users
  resources :historicos

  resources :receita_medicas

  root      :to => 'welcome#index'
  resources :principio_ativos
  resources :medicamentos
  resources :farmacias
  resources :enderecos

  match "/medicos" => "users#medicos"
  match "/pacientes" => "users#pacientes"
end

app/controllers/principio_ativos_controller.rb
class PrincipioAtivosController < ApplicationController
  # GET /principio_ativos
  # GET /principio_ativos.json
  def index
    @principio_ativos = PrincipioAtivo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @principio_ativos }
    end
  end

  # GET /principio_ativos/1
  # GET /principio_ativos/1.json
  def show
    @principio_ativo = PrincipioAtivo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @principio_ativo }
    end
  end

  # GET /principio_ativos/new
  # GET /principio_ativos/new.json
  def new
    @principio_ativo = PrincipioAtivo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @principio_ativo }
    end
  end

  # GET /principio_ativos/1/edit
  def edit
    @principio_ativo = PrincipioAtivo.find(params[:id])
  end

  # POST /principio_ativos
  # POST /principio_ativos.json
  def create
    @principio_ativo = PrincipioAtivo.new(params[:principio_ativo])

    respond_to do |format|
      if @principio_ativo.save
        format.html { redirect_to @principio_ativo, notice: 'Principio ativo was successfully created.' }
        format.json { render json: @principio_ativo, status: :created, location: @principio_ativo }
      else
        format.html { render action: "new" }
        format.json { render json: @principio_ativo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /principio_ativos/1
  # PUT /principio_ativos/1.json
  def update
    @principio_ativo = PrincipioAtivo.find(params[:id])

    respond_to do |format|
      if @principio_ativo.update_attributes(params[:principio_ativo])
        format.html { redirect_to @principio_ativo, notice: 'Principio ativo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @principio_ativo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /principio_ativos/1
  # DELETE /principio_ativos/1.json
  def destroy
    @principio_ativo = PrincipioAtivo.find(params[:id])
    @principio_ativo.destroy

    respond_to do |format|
      format.html { redirect_to principio_ativos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/principio_ativos_helper.rb
module PrincipioAtivosHelper
end

app/views/principio_ativos/_form.html.erb
<%= form_for @principio_ativo, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> /Principio Ativo</legend>

    <div class="control-group">
      <%= f.label :nome, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :nome, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', principio_ativos_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/principio_ativos/index.html.erb
<h1>Principio Ativos</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nome</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @principio_ativos.each do |principio_ativo| %>
      <tr>
        <td><%= principio_ativo.id %></td>
        <td><%= link_to principio_ativo.nome, principio_ativo_path(principio_ativo) %></td>
        <td>
          <%= link_to 'Edit', edit_principio_ativo_path(principio_ativo), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', principio_ativo_path(principio_ativo), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_principio_ativo_path, :class => 'btn btn-primary' %>

app/views/principio_ativos/show.html.erb
<h1>/Principio Ativo</h1>

<p>
  <b>Nome</b><br>
  <%= @principio_ativo.nome %>
</p>

<div class="form-actions">
  <%= link_to 'Back', principio_ativos_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_principio_ativo_path(@principio_ativo), :class => 'btn' %>
  <%= link_to 'Delete', principio_ativo_path(@principio_ativo), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>