config/routes.rb
PrescriptionIntegration::Application.routes.draw do

  resources :medicos_autorizados

  get "venda/search"

  get "api/sign_in"

  get "receita_medicas/show_for_farmacia"
  
  get "receita_medicas/show_for_medico"
  get "receita_medicas/search"

  post "receita_medicas/vender"
  
  devise_for :users
  # ,  
  #             :controllers => {
  #               :registrations => 'devise/registrations',
  #               :sessions => 'devise/sessions',
  #             }
  
  resources :users
  resources :historicos

  resources :receita_medicas

  root      :to => 'welcome#index'
  resources :principio_ativos
  resources :medicamentos
  resources :farmacias
  resources :enderecos

  match "/medicos" => "users#medicos"
  match "/pacientes" => "users#pacientes"
end

app/models/historico.rb
class Historico < ActiveRecord::Base
end

app/controllers/historicos_controller.rb
class HistoricosController < ApplicationController
  # GET /historicos
  # GET /historicos.json
  def index
    @historicos = Historico.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @historicos }
    end
  end

  # GET /historicos/1
  # GET /historicos/1.json
  def show
    @historico = Historico.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @historico }
    end
  end

  # GET /historicos/new
  # GET /historicos/new.json
  def new
    @historico = Historico.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @historico }
    end
  end

  # GET /historicos/1/edit
  def edit
    @historico = Historico.find(params[:id])
  end

  # POST /historicos
  # POST /historicos.json
  def create
    @historico = Historico.new(params[:historico])

    respond_to do |format|
      if @historico.save
        format.html { redirect_to @historico, notice: 'Historico was successfully created.' }
        format.json { render json: @historico, status: :created, location: @historico }
      else
        format.html { render action: "new" }
        format.json { render json: @historico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /historicos/1
  # PUT /historicos/1.json
  def update
    @historico = Historico.find(params[:id])

    respond_to do |format|
      if @historico.update_attributes(params[:historico])
        format.html { redirect_to @historico, notice: 'Historico was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @historico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /historicos/1
  # DELETE /historicos/1.json
  def destroy
    @historico = Historico.find(params[:id])
    @historico.destroy

    respond_to do |format|
      format.html { redirect_to historicos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/historicos_helper.rb
module HistoricosHelper
end

app/views/historicos/_form.html.erb
<%= form_for(@historico) do |f| %>
  <% if @historico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@historico.errors.count, "error") %> prohibited this historico from being saved:</h2>

      <ul>
      <% @historico.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/historicos/edit.html.erb
<h1>Editing historico</h1>

<%= render 'form' %>

<%= link_to 'Show', @historico %> |
<%= link_to 'Back', historicos_path %>

app/views/historicos/index.html.erb
<h1>Listing historicos</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Descricao</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @historicos.each do |historico| %>
  <tr>
    <td><%= historico.nome %></td>
    <td><%= historico.descricao %></td>
    <td><%= link_to 'Show', historico %></td>
    <td><%= link_to 'Edit', edit_historico_path(historico) %></td>
    <td><%= link_to 'Destroy', historico, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Historico', new_historico_path %>

app/views/historicos/new.html.erb
<h1>New historico</h1>

<%= render 'form' %>

<%= link_to 'Back', historicos_path %>

app/views/historicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @historico.nome %>
</p>

<p>
  <b>Descricao:</b>
  <%= @historico.descricao %>
</p>


<%= link_to 'Edit', edit_historico_path(@historico) %> |
<%= link_to 'Back', historicos_path %>