config/routes.rb
PrescriptionIntegration::Application.routes.draw do

  resources :medicos_autorizados

  get "venda/search"

  get "api/sign_in"

  get "receita_medicas/show_for_farmacia"
  
  get "receita_medicas/show_for_medico"
  get "receita_medicas/search"

  post "receita_medicas/vender"
  
  devise_for :users
  # ,  
  #             :controllers => {
  #               :registrations => 'devise/registrations',
  #               :sessions => 'devise/sessions',
  #             }
  
  resources :users
  resources :historicos

  resources :receita_medicas

  root      :to => 'welcome#index'
  resources :principio_ativos
  resources :medicamentos
  resources :farmacias
  resources :enderecos

  match "/medicos" => "users#medicos"
  match "/pacientes" => "users#pacientes"
end

app/models/medicos_autorizado.rb
class MedicosAutorizado < ActiveRecord::Base
	belongs_to :user
	belongs_to :medico, :class_name => "User"
end

app/controllers/medicos_autorizados_controller.rb
class MedicosAutorizadosController < ApplicationController

  # POST /medicos_autorizados
  # POST /medicos_autorizados.json
  def create
    @medicos_autorizado = current_user.medicos_autorizados.build(:medico_id => params[:medico_id])

    respond_to do |format|
      if @medicos_autorizado.save
        flash[:notice] = "Medico adicionado"
        format.html { redirect_to user_path(current_user), notice: 'Medicos autorizado was successfully created.' }
        format.json { render json: @medicos_autorizado, status: :created, location: @medicos_autorizado }
      else
        flash[:error] = "Medico nao adicionado"
        format.html { render action: "new" }
        format.json { render json: @medicos_autorizado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicos_autorizados/1
  # DELETE /medicos_autorizados/1.json
  def destroy
    @medicos_autorizado = current_user.medicos_autorizados.find(params[:id])
    @medicos_autorizado.destroy

    respond_to do |format|
      format.html { redirect_to current_user }
      format.json { head :no_content }
    end
  end
end

app/helpers/medicos_autorizados_helper.rb
module MedicosAutorizadosHelper
end

app/views/medicos_autorizados/_form.html.erb
<%= form_for(@medicos_autorizado) do |f| %>
  <% if @medicos_autorizado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medicos_autorizado.errors.count, "error") %> prohibited this medicos_autorizado from being saved:</h2>

      <ul>
      <% @medicos_autorizado.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :medico_id %><br />
    <%= f.number_field :medico_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medicos_autorizados/edit.html.erb
<h1>Editing medicos_autorizado</h1>

<%= render 'form' %>

<%= link_to 'Show', @medicos_autorizado %> |
<%= link_to 'Back', medicos_autorizados_path %>

app/views/medicos_autorizados/index.html.erb
<h1>Listing medicos_autorizados</h1>

<table>
  <tr>
    <th>User</th>
    <th>Medico</th>
    <th>Create</th>
    <th>Destroy</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @medicos_autorizados.each do |medicos_autorizado| %>
  <tr>
    <td><%= medicos_autorizado.user_id %></td>
    <td><%= medicos_autorizado.medico_id %></td>
    <td><%= medicos_autorizado.create %></td>
    <td><%= medicos_autorizado.destroy %></td>
    <td><%= link_to 'Show', medicos_autorizado %></td>
    <td><%= link_to 'Edit', edit_medicos_autorizado_path(medicos_autorizado) %></td>
    <td><%= link_to 'Destroy', medicos_autorizado, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Medicos autorizado', new_medicos_autorizado_path %>

app/views/medicos_autorizados/new.html.erb
<h1>New medicos_autorizado</h1>

<%= render 'form' %>

<%= link_to 'Back', medicos_autorizados_path %>

app/views/medicos_autorizados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @medicos_autorizado.user_id %>
</p>

<p>
  <b>Medico:</b>
  <%= @medicos_autorizado.medico_id %>
</p>

<%= link_to 'Edit', edit_medicos_autorizado_path(@medicos_autorizado) %> |
<%= link_to 'Back', medicos_autorizados_path %>